// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bpnnxjqhpbchcqdwcsvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwbm54anFocGJjaGNxZHdjc3Z2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNTc0MjYsImV4cCI6MjA2ODgzMzQyNn0.T-fbbwuPvnrWhF4pYp0zKTkxFgWhxjX2b27uhXGCpGw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});